"""Data-access layer. All SQL goes through SQLAlchemy Core table objects from ``degreeplan.db.tables``.

Repositories take an explicit ``Connection`` and never commit: the caller owns the transaction.
Only bound parameters are used (no string-built SQL).
"""
from __future__ import annotations

from typing import Any

from sqlalchemy.engine import CursorResult, Result


def one(result: Result) -> dict[str, Any] | None:
    row = result.mappings().first()
    return dict(row) if row else None


def all_rows(result: Result) -> list[dict[str, Any]]:
    return [dict(r) for r in result.mappings().all()]


def new_id(result: CursorResult) -> int:
    """Primary key generated by an INSERT."""
    key = result.inserted_primary_key
    if key is None:  # pragma: no cover - defensive; single-row inserts always return a key
        raise RuntimeError("INSERT did not return a primary key")
    return int(key[0])
