"""Sample data for LOCAL DEVELOPMENT AND TESTS ONLY.

It never contains credentials: passwords are supplied by the caller (randomly generated by the
``dev seed`` command and shown once). It refuses to run in production.
"""
from __future__ import annotations

from collections.abc import Mapping

import sqlalchemy as sa
from sqlalchemy.engine import Connection

from .. import clock
from ..config import Settings
from ..db.tables import course_prerequisites, courses, program_requirements, programs
from ..repositories import people
from ..repositories import users as users_repo
from ..security.passwords import PasswordService

# (username, role, first_name, last_name, advisor_username)
SAMPLE_PEOPLE = (
    ("admin", "admin", None, None, None),
    ("teacher1", "teacher", "Tina", "Teacher", None),
    ("teacher2", "teacher", "Theo", "Tutor", None),
    ("alice", "student", "Alice", "Anderson", "teacher1"),
    ("bob", "student", "Bob", "Baker", "teacher1"),
    ("carol", "student", "Carol", "Clark", "teacher2"),
)
SAMPLE_USERNAMES = tuple(p[0] for p in SAMPLE_PEOPLE)

_COURSES = (
    (1, "CS101", "Intro to Programming", 4),
    (2, "CS201", "Data Structures", 4),
    (3, "CS301", "Algorithms", 3),
    (4, "MATH101", "Calculus I", 4),
    (5, "MATH201", "Discrete Mathematics", 3),
    (6, "CS350", "Software Engineering", 3),
)
_PREREQS = ((2, 1), (3, 2), (3, 5), (5, 4), (6, 2))


def seed_sample_data(
    users: Connection,
    plans: Connection,
    *,
    settings: Settings,
    passwords: PasswordService,
    credentials: Mapping[str, str],
) -> None:
    """Insert sample catalog + accounts. ``credentials`` maps each sample username to its password."""
    if settings.is_production:
        raise RuntimeError("Refusing to load sample data in production")
    missing = set(SAMPLE_USERNAMES) - set(credentials)
    if missing:
        raise ValueError(f"No password supplied for: {', '.join(sorted(missing))}")

    # Catalog (plans database)
    plans.execute(sa.insert(programs).values(id=1, code="BSCS", name="B.S. Computer Science", total_credits=120))
    plans.execute(
        sa.insert(courses),
        [{"id": i, "code": c, "title": t, "credits": cr, "description": None} for i, c, t, cr in _COURSES],
    )
    plans.execute(
        sa.insert(course_prerequisites), [{"course_id": c, "prerequisite_id": p} for c, p in _PREREQS]
    )
    plans.execute(
        sa.insert(program_requirements), [{"program_id": 1, "course_id": i} for i, *_ in _COURSES]
    )
    plans.commit()

    # Accounts (users database)
    now = clock.now()
    teacher_ids: dict[str, int] = {}
    for username, role, first, last, advisor in SAMPLE_PEOPLE:
        user_id = users_repo.create(
            users,
            username=username,
            password_hash=passwords.hash(credentials[username]),
            role=role,
            now=now,
        )
        if role == "teacher":
            teacher_ids[username] = people.create_teacher(
                users, user_id=user_id, first_name=first or "", last_name=last or "", department="Computer Science"
            )
        elif role == "student":
            people.create_student(
                users,
                user_id=user_id,
                first_name=first or "",
                last_name=last or "",
                program_id=1,
                advisor_id=teacher_ids.get(advisor) if advisor else None,
            )
    users.commit()
